#+TITLE: Urðr (URDR - Universal Relational Database Reflection)

Urðr (named after one of the [[https://en.wikipedia.org/wiki/Norns][Norns]] in Norse mythology) is an application that
can be used to map, display and register information in a relational database.
It uses information only from the database itself (reflection) in order to
display data and relations between them. This requires some rules to be followed
when designing the database. The rules are often based on common principles for
designing databases.

The rules are laid out here: [[./docs/selvdokumenterende-baser.org][selvdokumenterende-baser]] (currently only in
norwegian).

The application is designed for archivists, who need to map databases, find how
the information is connected, and create access databases from the original
database.

Urðr can analyze the original database and find which tables, columns and
relations have been used the most, and create an ER diagram of these
relations.

After a original database has been analyzed, an access database can be made
based on the rules that Urðr uses to present the data.

* Requirements
Linux or macOS

* Installation

#+begin_src bash
> git clone https://github.com/fkirkholt/urd-backend urdr
> cd urdr
> pip install -r requirements.txt
#+end_src

Also install the [[https://github.com/fkirkholt/urd-frontend][frontend]] before starting the application.

* Starting web server

#+begin_src bash
> python3 main.py
#+end_src
